server:
  port: 8180

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Keycloak_SpringBoot
          jwk-set-uri: http://localhost:8080/auth/realms/Keycloak_SpringBoot/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
